### ISSUE TITLE
Possible to use the demo myself?

### ISSUE THREAD

**Issue by justin-capalbo** [alexkuang/vim-ll#1]
l have been planning to give a VIM lunch and learn at work.  I really love your presentation and I think it captures the essence of why VIM is good in a nice and visual way.  Would you mind if I used it and gave you credit?  Thanks!

**Comment by alexkuang** [comment]
No problem, go ahead and use!

**Comment by justin-capalbo** [comment]
Thanks Alex!  I'm going to make a branch of the repo locally and make some changes to make the presentation more relevant for my organization.  I'm hoping that modal editing catches on!
